name = "hono_demo"

compatibility_date = "2024-04-01"
compatibility_flags = ['nodejs_compat']

[[kv_namespaces]]
binding = "hono_kv_demo"
id = "ca4b064ef936455db1ba09a9451d9f04"

[[d1_databases]]
binding = "DB"
database_name = "hono-dev"
database_id = "b0a65a18-20b6-40c4-ac63-89fc44d234b7"