name = "hono_demo"

compatibility_date = "2024-04-01"
compatibility_flags = ['nodejs_compat']

kv_namespaces = [
  { binding = "hono_kv_demo", preview_id = "eaa9b2c1c70c4798a883b6e73d4b4895", id = "eaa9b2c1c70c4798a883b6e73d4b4895" }
]

[[d1_databases]]
binding = "DB"
database_name = "hono-dev"
database_id = "b0a65a18-20b6-40c4-ac63-89fc44d234b7"