name = "hono_demo"

compatibility_date = "2024-04-01"
compatibility_flags = ['nodejs_compat']

kv_namespaces = [
  { binding = "BLOG_EXAMPLE", preview_id = "your-id", id = "your-id" }
]

[[d1_databases]]
binding = "DB"
database_name = "hono-dev"
database_id = "b0a65a18-20b6-40c4-ac63-89fc44d234b7"